# Generated by Django 3.0.2 on 2020-01-16 07:37

from django.db import migrations, models
import django.db.models.manager
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=50, verbose_name='Fullname')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='SA', unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_email', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=15, verbose_name='Password')),
                ('password_confirm', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
